/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActionRequest } from '../../models/action-request';
import { ActionResponse } from '../../models/action-response';

export interface DispatchAction$Params {
      body: ActionRequest
}

export function dispatchAction(http: HttpClient, rootUrl: string, params: DispatchAction$Params, context?: HttpContext): Observable<StrictHttpResponse<ActionResponse>> {
  const rb = new RequestBuilder(rootUrl, dispatchAction.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ActionResponse>;
    })
  );
}

dispatchAction.PATH = '/game/action';
