/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SaveRequest } from '../../models/save-request';
import { SaveSummary } from '../../models/save-summary';

export interface CreateSave$Params {
      body: SaveRequest
}

export function createSave(http: HttpClient, rootUrl: string, params: CreateSave$Params, context?: HttpContext): Observable<StrictHttpResponse<SaveSummary>> {
  const rb = new RequestBuilder(rootUrl, createSave.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SaveSummary>;
    })
  );
}

createSave.PATH = '/saves';
