import { computed, effect, Injectable, inject, signal } from '@angular/core';
import { CameraService } from '../camera/camera.service';
import { WorldGeneratorService, CHUNK_SIZE } from '../generation/world-generator.service';
import { Chunk, ChunkCoord } from '../../models/chunk';
import { HexData } from '../../models/hex-data';

const SQRT3 = Math.sqrt(3);
const VISIBLE_BUFFER = 2;
const EVICTION_DISTANCE = 5;

function chunkKey(cx: number, cy: number): string {
  return `${cx},${cy}`;
}

@Injectable({ providedIn: 'root' })
export class ChunkManagerService {
  private readonly camera = inject(CameraService);
  private readonly generator = inject(WorldGeneratorService);
  private readonly cache = new Map<string, Chunk>();

  private generationQueue: ChunkCoord[] = [];
  private generating = false;

  /** Which chunk coords overlap the current viewport. */
  readonly visibleChunkCoords = computed<ChunkCoord[]>(() => {
    const vp = this.camera.viewport();
    return this.getChunkCoordsInRect(vp.left, vp.top, vp.right, vp.bottom);
  });

  /** Loaded chunks that are currently visible. Updated progressively as chunks generate. */
  private readonly _visibleChunks = signal<Chunk[]>([]);
  readonly visibleChunks = this._visibleChunks.asReadonly();

  constructor() {
    // React to viewport changes — queue missing chunks
    effect(() => {
      const coords = this.visibleChunkCoords();
      this.queueChunkGeneration(coords);
    });
  }

  /** Get the chunk coords that overlap a world-coordinate rectangle. */
  getChunkCoordsInRect(
    left: number,
    top: number,
    right: number,
    bottom: number,
  ): ChunkCoord[] {
    const hexSize = 30;

    const corners = [
      { x: left, y: top },
      { x: right, y: top },
      { x: left, y: bottom },
      { x: right, y: bottom },
    ];

    let minCX = Infinity;
    let maxCX = -Infinity;
    let minCY = Infinity;
    let maxCY = -Infinity;

    for (const { x, y } of corners) {
      const q = ((2 / 3) * x) / hexSize;
      const r = ((-1 / 3) * x + (SQRT3 / 3) * y) / hexSize;
      const cx = Math.floor(q / CHUNK_SIZE);
      const cy = Math.floor(r / CHUNK_SIZE);
      if (cx < minCX) minCX = cx;
      if (cx > maxCX) maxCX = cx;
      if (cy < minCY) minCY = cy;
      if (cy > maxCY) maxCY = cy;
    }

    minCX -= VISIBLE_BUFFER;
    maxCX += VISIBLE_BUFFER;
    minCY -= VISIBLE_BUFFER;
    maxCY += VISIBLE_BUFFER;

    const coords: ChunkCoord[] = [];
    for (let cx = minCX; cx <= maxCX; cx++) {
      for (let cy = minCY; cy <= maxCY; cy++) {
        coords.push({ cx, cy });
      }
    }
    return coords;
  }

  /** Discard all cached chunks (e.g. when starting a new game with a new seed). */
  clearCache(): void {
    this.cache.clear();
    this.generationQueue = [];
    this.generating = false;
    this._visibleChunks.set([]);
  }

  /** Mark the chunk containing hex (q, r) as dirty. */
  markDirty(q: number, r: number): void {
    const cx = Math.floor(q / CHUNK_SIZE);
    const cy = Math.floor(r / CHUNK_SIZE);
    const chunk = this.cache.get(chunkKey(cx, cy));
    if (chunk) {
      chunk.dirty = true;
    }
  }

  /** Look up a hex from cache, generating the chunk if needed (synchronous). */
  getHex(q: number, r: number): HexData | null {
    const cx = Math.floor(q / CHUNK_SIZE);
    const cy = Math.floor(r / CHUNK_SIZE);
    const key = chunkKey(cx, cy);
    let chunk = this.cache.get(key);
    if (!chunk) {
      chunk = this.generator.generate({ cx, cy });
      this.cache.set(key, chunk);
    }
    return chunk.hexes.get(`${q},${r}`) ?? null;
  }

  private queueChunkGeneration(coords: ChunkCoord[]): void {
    const missing: ChunkCoord[] = [];
    const ready: Chunk[] = [];

    for (const coord of coords) {
      const key = chunkKey(coord.cx, coord.cy);
      const cached = this.cache.get(key);
      if (cached) {
        ready.push(cached);
      } else {
        missing.push(coord);
      }
    }

    // Immediately show whatever we have cached
    this._visibleChunks.set(ready);

    // Queue missing chunks for async generation
    this.generationQueue = missing;
    if (!this.generating && missing.length > 0) {
      this.generating = true;
      this.processQueue(coords);
    }
  }

  private processQueue(allCoords: ChunkCoord[]): void {
    if (this.generationQueue.length === 0) {
      this.generating = false;
      this.evictDistantChunks(allCoords);
      return;
    }

    const coord = this.generationQueue.shift()!;
    const key = chunkKey(coord.cx, coord.cy);

    // Skip if already cached (e.g. generated by getHex() in between)
    if (!this.cache.has(key)) {
      const chunk = this.generator.generate(coord);
      this.cache.set(key, chunk);
    }

    // Update signal with all currently cached visible chunks
    const currentCoords = this.visibleChunkCoords();
    const updated: Chunk[] = [];
    for (const c of currentCoords) {
      const k = chunkKey(c.cx, c.cy);
      const cached = this.cache.get(k);
      if (cached) updated.push(cached);
    }
    this._visibleChunks.set(updated);

    // Yield to browser, then process next
    setTimeout(() => this.processQueue(currentCoords), 0);
  }

  private evictDistantChunks(visibleCoords: ChunkCoord[]): void {
    if (this.cache.size < 50) return;

    for (const [key, chunk] of this.cache) {
      const isNearVisible = visibleCoords.some(
        (vc) =>
          Math.abs(vc.cx - chunk.coord.cx) <= EVICTION_DISTANCE &&
          Math.abs(vc.cy - chunk.coord.cy) <= EVICTION_DISTANCE,
      );
      if (!isNearVisible) {
        this.cache.delete(key);
      }
    }
  }
}
