/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChunkResponse } from '../../models/chunk-response';

export interface GetChunks$Params {
  seed: number;

/**
 * Semicolon-separated chunk coordinates, e.g. 0,0;1,0;-1,1
 */
  coords: string;
}

export function getChunks(http: HttpClient, rootUrl: string, params: GetChunks$Params, context?: HttpContext): Observable<StrictHttpResponse<ChunkResponse>> {
  const rb = new RequestBuilder(rootUrl, getChunks.PATH, 'get');
  if (params) {
    rb.query('seed', params.seed, {});
    rb.query('coords', params.coords, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ChunkResponse>;
    })
  );
}

getChunks.PATH = '/world/chunks';
