/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ActionRequest {

  /**
   * Game action (polymorphic, discriminated by 'type' field)
   */
  action: {
};

  /**
   * Serialized game state JSON
   */
  state: string;
}
