/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AiTurnRequest {

  /**
   * The AI player's ID
   */
  playerId: string;

  /**
   * Serialized game state JSON
   */
  state: string;
}
