/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HexData } from '../models/hex-data';
export interface ChunkData {
  cx: number;
  cy: number;
  hexes: {
[key: string]: HexData;
};
}
