/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StellarObject } from '../models/stellar-object';
export interface HexData {
  anomaly?: string | null;
  inNebula?: boolean;
  object?: StellarObject;
  q: number;
  r: number;
  tradeHub?: boolean;
}
