/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SaveData {
  cameraJson?: string | null;
  id: number;
  playerName?: string | null;
  saveName: string;
  stateJson: string;
  turn?: number;
  updatedAt: string;
  waypointsJson?: string | null;
}
