/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SaveRequest {
  cameraJson?: string | null;
  playerName?: string | null;
  saveName?: string;

  /**
   * Serialized game state JSON
   */
  stateJson: string;
  turn?: number;
  waypointsJson?: string | null;
}
