/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SaveSummary {
  id: number;
  playerName?: string | null;
  saveName: string;
  turn: number;
  updatedAt: string;
}
