/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HexCoordDto } from '../models/hex-coord-dto';
export interface StellarObject {
  orbitAnchor?: HexCoordDto;
  resources?: ({
'energy'?: number;
'minerals'?: number;
'alloys'?: number;
'credits'?: number;
}) | null;
  size: number;
  subtype?: string | null;
  type: string;
  velocity?: HexCoordDto;
}
