/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StellarObject {
  resources?: ({
'energy'?: number;
'minerals'?: number;
'alloys'?: number;
'credits'?: number;
}) | null;
  size: number;
  subtype?: string | null;
  type: string;
}
