/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SessionInfo } from '../../models/session-info';

export interface GetSession$Params {
}

export function getSession(http: HttpClient, rootUrl: string, params?: GetSession$Params, context?: HttpContext): Observable<StrictHttpResponse<SessionInfo | null>> {
  const rb = new RequestBuilder(rootUrl, getSession.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SessionInfo | null>;
    })
  );
}

getSession.PATH = '/auth/me';
